name: maxcso Build

on:
  workflow_dispatch:
    inputs:
      maxcso_ref:
        description: 'maxcso GitHub branch, tag, or SHA (e.g. "v1.13.0")'
        required: true
        type: string
      auto-merge:
        description: 'Auto-merge pull request?'
        required: true
        type: boolean
        default: true
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-linux:
    name: build-linux ${{ matrix.nodejs_arch }}
    strategy:
      matrix:
        include:
          - docker_image: i386/ubuntu:latest
            docker_arch: linux/386
            nodejs_arch: ia32
          - docker_image: ubuntu:latest
            docker_arch: linux/amd64
            nodejs_arch: amd64
          - docker_image: ubuntu:latest
            docker_arch: linux/arm/v7
            nodejs_arch: armv7
          - docker_image: ubuntu:latest
            docker_arch: linux/arm64/v8
            nodejs_arch: arm64v8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: unknownbrackets/maxcso
          ref: ${{ env.MAME_REF }}
      - uses: docker/setup-qemu-action@v3
      - run: |
          {
            echo "#!/usr/bin/env bash"
            echo "set -euo pipefail"

            echo "sudo apt-get update"
            echo "sudo apt-get install -y build-essential pkgconf zlib1g-dev liblz4-dev libuv1-dev"
            echo "make -j$(nproc)"
            echo "file maxcso"

            echo "sudo apt-get install -y binutils"
            echo "ls -al maxcso"
            echo "strip maxcso"
            echo "ls -al maxcso"
          } > "build.sh"
          chmod +x build.sh
      - run: |
          docker run --rm \
            --platform "${DOCKER_ARCH}" \
            --volume "$(pwd):/build" \
            --workdir "/build" \
            "${DOCKER_IMAGE}"
            ./build.sh
        env:
          DOCKER_IMAGE: ${{ matrix.docker_image }}
          DOCKER_ARCH: ${{ matrix.docker_arch }}
      - name: Rename binary
        run: |
          dir="artifacts/bin/linux/${{ matrix.nodejs_arch }}"
          mkdir -p "${dir}"
          mv maxcso "${dir}/"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.nodejs_arch }}-${{ github.sha }}
          path: artifacts/**/maxcso
          if-no-files-found: error

  build-macos:
    name: build-macos ${{ matrix.nodejs_arch }}
    strategy:
      matrix:
        include:
          - os: macos-13
            nodejs_arch: x64
          - os: macos-14
            nodejs_arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: unknownbrackets/maxcso
          ref: ${{ env.MAME_REF }}
      - name: Install dependencies
        run: brew install --overwrite lz4 libuv libdeflate
      - name: Build
        run: |
          make "-j$(sysctl -n hw.physicalcpu)"
          file maxcso
      - name: Strip binary
        run: |
          ls -al maxcso
          strip maxcso
          ls -al maxcso
      - name: Rename binary
        run: |
          dir="artifacts/bin/darwin/${{ matrix.nodejs_arch }}"
          mkdir -p "${dir}"
          mv maxcso "${dir}/"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.nodejs_arch }}-${{ github.sha }}
          path: artifacts/**/maxcso
          if-no-files-found: error

  build-windows:
    name: build-windows ${{ matrix.nodejs_arch }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: x64
            nodejs_arch: x64
          - platform: Win32
            nodejs_arch: ia32
    # Note: various .vcxproj files require v141_xp, which is why this isn't latest
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          repository: unknownbrackets/maxcso
          ref: ${{ env.MAME_REF }}
      - uses: microsoft/setup-msbuild@v2
      - name: Build
        run: |
          msbuild cli/maxcso.sln -maxcpucount /property:Configuration=Release "/property:Platform=${{ matrix.platform }}"
#      - name: Strip binary
#        run: |
#          ls -al maxcso.exe
#          strip maxcso.exe
#          ls -al maxcso.exe
      - name: Rename binary
        run: |
          $Dir = artifacts\bin\win32\${{ matrix.nodejs_arch }}
          mkdir "$Dir"
          mv maxcso.exe "$Dir\"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.platform }}-${{ github.sha }}
          path: artifacts/**/maxcso.exe
          if-no-files-found: error

  git-update:
    needs:
      - build-linux
      - build-macos
      - build-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
